param(
    [string]$Version,
    [string]$RcNumber,
    [string]$SpecialVersion = "",
    [string]$IsRealRelease  = "false",
    [string]$RunId,
    [string]$Repository,
    [string]$Actor,
    [string]$CommitSha,
    [string]$BranchName,
    [string]$InstallerPath  = "",
    [string]$InstallerFiles = "",
    [string]$ReleaseDate,
    [string]$ServerUrl      = "https://github.com"
)

# ── Pre-compute display values ──────────────────────────────────────────────
$releaseName = "SDS2 $Version RC$RcNumber"
if ($SpecialVersion) { $releaseName += " ($SpecialVersion)" }

$releaseTypeStr     = if ($IsRealRelease -eq "true") { "Major / Minor" } else { "RC / Pre-release" }
$signingStr         = if ($IsRealRelease -eq "true") { '<span class="yes">&#x2705; Yes</span>' } else { 'N/A (non-real release)' }
$runUrl             = "$ServerUrl/$Repository/actions/runs/$RunId"
$repoUrl            = "$ServerUrl/$Repository"
$installerFilesCell = if ($InstallerFiles) { $InstallerFiles } else { '<span class="tbd">TBD</span>' }
$installerPathCell  = if ($InstallerPath)  { $InstallerPath }  else { '<span class="tbd">TBD</span>' }

# ── Generate HTML ───────────────────────────────────────────────────────────
$html = @"
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>$releaseName - QA Handoff</title>
  <style>
    body  { font-family: Arial, sans-serif; margin: 40px; color: #172B4D; }
    h1    { color: #0052CC; }
    h2    { color: #253858; border-bottom: 2px solid #DFE1E6; padding-bottom: 6px; margin-top: 32px; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
    th    { background: #F4F5F7; text-align: left; padding: 8px 12px; border: 1px solid #DFE1E6; }
    td    { padding: 8px 12px; border: 1px solid #DFE1E6; }
    .yes  { color: #006644; font-weight: bold; }
    .no   { color: #BF2600; font-weight: bold; }
    .tbd  { color: #6B778C; font-style: italic; }
    .note { background: #FFFAE6; border-left: 4px solid #FF991F; padding: 10px 14px; margin: 12px 0; border-radius: 3px; }
    a     { color: #0052CC; }
  </style>
</head>
<body>

<h1>Desktop Application Release Checklist - QA Handoff</h1>
<div class="note">
  <strong>MOCK</strong> &mdash; Auto-generated by GitHub Actions Run
  <a href="$runUrl">#$RunId</a> on $ReleaseDate.<br>
  Fields marked <em class="tbd">TBD</em> must be completed manually before formal QA handoff.
</div>

<h2>1. Release Identification</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Application Name</td><td>SDS2</td></tr>
  <tr><td>2</td><td>Application Type</td><td>Desktop Application</td></tr>
  <tr><td>3</td><td>Release Name</td><td>$releaseName</td></tr>
  <tr><td>4</td><td>Version Number</td><td>$Version</td></tr>
  <tr><td>5</td><td>Build Number / CI Job ID</td><td>$RunId</td></tr>
  <tr><td>6</td><td>Release Type</td><td>$releaseTypeStr</td></tr>
  <tr><td>7</td><td>Release Date</td><td>$ReleaseDate</td></tr>
</table>

<h2>2. Source &amp; Build Information</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Source Repository</td><td><a href="$repoUrl">$Repository</a></td></tr>
  <tr><td>2</td><td>Branch / Tag</td><td>$BranchName</td></tr>
  <tr><td>3</td><td>Commit ID</td><td><code>$CommitSha</code></td></tr>
  <tr><td>4</td><td>Build Tool / Pipeline</td><td>GitHub Actions</td></tr>
  <tr><td>5</td><td>Build Triggered By</td><td>$Actor</td></tr>
  <tr><td>6</td><td>Build Status</td><td><span class="yes">&#x2705; Success</span></td></tr>
</table>

<h2>3. Installer Details</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Installer Type</td><td>EXE (NSIS)</td></tr>
  <tr><td>2</td><td>Installer File Name(s)</td><td>$installerFilesCell</td></tr>
  <tr><td>3</td><td>Installer Version</td><td>$Version</td></tr>
  <tr><td>4</td><td>Installer Size</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>5</td><td>Target OS</td><td>Windows / Linux</td></tr>
</table>

<h2>4. Installer Signing &amp; Security Validation</h2>
<table>
  <tr><th>#</th><th>Check</th><th>Status</th></tr>
  <tr><td>1</td><td>Installer Digitally Signed</td><td>$signingStr</td></tr>
  <tr><td>2</td><td>Signing Certificate Name</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Certificate Expiry Date</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Installer Signature Verified</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>5</td><td>Antivirus / Malware Scan Completed</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>5. Artifact Location (QA Pickup Point)</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Common Path / Network Location</td><td>$installerPathCell</td></tr>
  <tr><td>2</td><td>Folder Structure Verified</td><td><span class="yes">&#x2705; Yes</span></td></tr>
  <tr><td>3</td><td>QA Read Access Verified</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Previous Release Retained</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>6. System Requirements &amp; Prerequisites</h2>
<table>
  <tr><th>#</th><th>Category</th><th>Details</th></tr>
  <tr><td>1</td><td>Supported OS Versions</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>Minimum Hardware Requirements</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Software Prerequisites</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Prerequisites Bundled</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>7. Installation &amp; Upgrade Validation</h2>
<table>
  <tr><th>#</th><th>Check</th><th>Status</th></tr>
  <tr><td>1</td><td>Fresh Install Tested</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>2</td><td>Upgrade from Previous Version Tested</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>3</td><td>Uninstall Tested</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>4</td><td>Silent Install Supported</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>5</td><td>Default Install Path Verified</td><td><span class="tbd">TBD - QA</span></td></tr>
</table>

<h2>8. Configuration &amp; Data Considerations</h2>
<table>
  <tr><th>#</th><th>Item</th><th>Details</th></tr>
  <tr><td>1</td><td>Post-Install Configuration Required</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>Config File Location</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Data Migration Required</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Backward Compatibility Confirmed</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>9. Pre-QA Validation (Dev / Installer Team)</h2>
<table>
  <tr><th>#</th><th>Validation</th><th>Status</th></tr>
  <tr><td>1</td><td>Application Launch Verified</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>Basic Smoke Test Completed</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>No Critical Install Errors Observed</td><td><span class="yes">&#x2705; Yes (build succeeded)</span></td></tr>
  <tr><td>4</td><td>Installer Logs Reviewed</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>10. Known Issues &amp; Limitations</h2>
<p class="tbd">None recorded at time of handoff. QA to document findings during testing.</p>

<h2>11. Rollback / Backout Plan</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Rollback Method</td><td>Uninstall + Install Previous Version</td></tr>
  <tr><td>2</td><td>Previous Stable Version</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Rollback Notes</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>12. QA Handoff Confirmation</h2>
<table>
  <tr><th>#</th><th>Role</th><th>Name</th><th>Date</th><th>Signature</th></tr>
  <tr><td>1</td><td>Release Owner</td><td>$Actor</td><td>$ReleaseDate</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>QA Lead</td><td><span class="tbd">TBD</span></td><td><span class="tbd">TBD</span></td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>13. References &amp; Attachments</h2>
<ul>
  <li>Build Run: <a href="$runUrl">GitHub Actions Run #$RunId</a></li>
  <li>Release Notes: <span class="tbd">TBD</span></li>
  <li>Installer Checksum / Hash: <span class="tbd">TBD</span></li>
  <li>Related Work Items: <span class="tbd">TBD</span></li>
</ul>

</body>
</html>
"@

# ── Write output ────────────────────────────────────────────────────────────
$null    = New-Item -ItemType Directory -Path "qa-handoff-report" -Force
$outFile = "qa-handoff-report\SDS2-$Version-RC$RcNumber-QA-Handoff.html"
$html | Out-File -FilePath $outFile -Encoding UTF8
Write-Host ">>> Mock Confluence checklist written to: $outFile"

param(
    [string]$Version,
    [string]$RcNumber,
    [string]$SpecialVersion = "",
    [string]$IsRealRelease  = "false",
    [string]$RunId,
    [string]$Repository,
    [string]$Actor,
    [string]$CommitSha,
    [string]$BranchName,
    [string]$InstallerPath  = "",
    [string]$InstallerFiles = "",
    [string]$ReleaseDate,
    [string]$ServerUrl      = "https://github.com"
)

# -- Pre-compute display values ----------------------------------------------
$releaseName = "SDS2 $Version RC$RcNumber"
if ($SpecialVersion) { $releaseName += " ($SpecialVersion)" }

$releaseTypeStr     = if ($IsRealRelease -eq "true") { "Major / Minor" } else { "RC / Pre-release" }
$signingStr         = if ($IsRealRelease -eq "true") { '<span class="yes">&#x2705; Yes</span>' } else { 'N/A (non-real release)' }
$runUrl             = "$ServerUrl/$Repository/actions/runs/$RunId"
$repoUrl            = "$ServerUrl/$Repository"
$installerFilesCell = if ($InstallerFiles) { $InstallerFiles } else { '<span class="tbd">TBD</span>' }
$installerPathCell  = if ($InstallerPath)  { $InstallerPath }  else { '<span class="tbd">TBD</span>' }

# -- Generate HTML -----------------------------------------------------------
$html = @"
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>$releaseName - QA Handoff</title>
  <style>
    body  { font-family: Arial, sans-serif; margin: 40px; color: #172B4D; }
    h1    { color: #0052CC; }
    h2    { color: #253858; border-bottom: 2px solid #DFE1E6; padding-bottom: 6px; margin-top: 32px; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 20px; }
    th    { background: #F4F5F7; text-align: left; padding: 8px 12px; border: 1px solid #DFE1E6; }
    td    { padding: 8px 12px; border: 1px solid #DFE1E6; }
    .yes  { color: #006644; font-weight: bold; }
    .no   { color: #BF2600; font-weight: bold; }
    .tbd  { color: #6B778C; font-style: italic; }
    .note { background: #FFFAE6; border-left: 4px solid #FF991F; padding: 10px 14px; margin: 12px 0; border-radius: 3px; }
    a     { color: #0052CC; }
  </style>
</head>
<body>

<h1>Desktop Application Release Checklist - QA Handoff</h1>
<div class="note">
  <strong>MOCK</strong> &mdash; Auto-generated by GitHub Actions Run
  <a href="$runUrl">#$RunId</a> on $ReleaseDate.<br>
  Fields marked <em class="tbd">TBD</em> must be completed manually before formal QA handoff.
</div>

<h2>1. Release Identification</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Application Name</td><td>SDS2</td></tr>
  <tr><td>2</td><td>Application Type</td><td>Desktop Application</td></tr>
  <tr><td>3</td><td>Release Name</td><td>$releaseName</td></tr>
  <tr><td>4</td><td>Version Number</td><td>$Version</td></tr>
  <tr><td>5</td><td>Build Number / CI Job ID</td><td>$RunId</td></tr>
  <tr><td>6</td><td>Release Type</td><td>$releaseTypeStr</td></tr>
  <tr><td>7</td><td>Release Date</td><td>$ReleaseDate</td></tr>
</table>

<h2>2. Source &amp; Build Information</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Source Repository</td><td><a href="$repoUrl">$Repository</a></td></tr>
  <tr><td>2</td><td>Branch / Tag</td><td>$BranchName</td></tr>
  <tr><td>3</td><td>Commit ID</td><td><code>$CommitSha</code></td></tr>
  <tr><td>4</td><td>Build Tool / Pipeline</td><td>GitHub Actions</td></tr>
  <tr><td>5</td><td>Build Triggered By</td><td>$Actor</td></tr>
  <tr><td>6</td><td>Build Status</td><td><span class="yes">&#x2705; Success</span></td></tr>
</table>

<h2>3. Installer Details</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Installer Type</td><td>EXE (NSIS)</td></tr>
  <tr><td>2</td><td>Installer File Name(s)</td><td>$installerFilesCell</td></tr>
  <tr><td>3</td><td>Installer Version</td><td>$Version</td></tr>
  <tr><td>4</td><td>Installer Size</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>5</td><td>Target OS</td><td>Windows / Linux</td></tr>
</table>

<h2>4. Installer Signing &amp; Security Validation</h2>
<table>
  <tr><th>#</th><th>Check</th><th>Status</th></tr>
  <tr><td>1</td><td>Installer Digitally Signed</td><td>$signingStr</td></tr>
  <tr><td>2</td><td>Signing Certificate Name</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Certificate Expiry Date</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Installer Signature Verified</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>5</td><td>Antivirus / Malware Scan Completed</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>5. Artifact Location (QA Pickup Point)</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Common Path / Network Location</td><td>$installerPathCell</td></tr>
  <tr><td>2</td><td>Folder Structure Verified</td><td><span class="yes">&#x2705; Yes</span></td></tr>
  <tr><td>3</td><td>QA Read Access Verified</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Previous Release Retained</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>6. System Requirements &amp; Prerequisites</h2>
<table>
  <tr><th>#</th><th>Category</th><th>Details</th></tr>
  <tr><td>1</td><td>Supported OS Versions</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>Minimum Hardware Requirements</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Software Prerequisites</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Prerequisites Bundled</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>7. Installation &amp; Upgrade Validation</h2>
<table>
  <tr><th>#</th><th>Check</th><th>Status</th></tr>
  <tr><td>1</td><td>Fresh Install Tested</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>2</td><td>Upgrade from Previous Version Tested</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>3</td><td>Uninstall Tested</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>4</td><td>Silent Install Supported</td><td><span class="tbd">TBD - QA</span></td></tr>
  <tr><td>5</td><td>Default Install Path Verified</td><td><span class="tbd">TBD - QA</span></td></tr>
</table>

<h2>8. Configuration &amp; Data Considerations</h2>
<table>
  <tr><th>#</th><th>Item</th><th>Details</th></tr>
  <tr><td>1</td><td>Post-Install Configuration Required</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>Config File Location</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Data Migration Required</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>4</td><td>Backward Compatibility Confirmed</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>9. Pre-QA Validation (Dev / Installer Team)</h2>
<table>
  <tr><th>#</th><th>Validation</th><th>Status</th></tr>
  <tr><td>1</td><td>Application Launch Verified</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>Basic Smoke Test Completed</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>No Critical Install Errors Observed</td><td><span class="yes">&#x2705; Yes (build succeeded)</span></td></tr>
  <tr><td>4</td><td>Installer Logs Reviewed</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>10. Known Issues &amp; Limitations</h2>
<p class="tbd">None recorded at time of handoff. QA to document findings during testing.</p>

<h2>11. Rollback / Backout Plan</h2>
<table>
  <tr><th>#</th><th>Field</th><th>Value</th></tr>
  <tr><td>1</td><td>Rollback Method</td><td>Uninstall + Install Previous Version</td></tr>
  <tr><td>2</td><td>Previous Stable Version</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>3</td><td>Rollback Notes</td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>12. QA Handoff Confirmation</h2>
<table>
  <tr><th>#</th><th>Role</th><th>Name</th><th>Date</th><th>Signature</th></tr>
  <tr><td>1</td><td>Release Owner</td><td>$Actor</td><td>$ReleaseDate</td><td><span class="tbd">TBD</span></td></tr>
  <tr><td>2</td><td>QA Lead</td><td><span class="tbd">TBD</span></td><td><span class="tbd">TBD</span></td><td><span class="tbd">TBD</span></td></tr>
</table>

<h2>13. References &amp; Attachments</h2>
<ul>
  <li>Build Run: <a href="$runUrl">GitHub Actions Run #$RunId</a></li>
  <li>Release Notes: <span class="tbd">TBD</span></li>
  <li>Installer Checksum / Hash: <span class="tbd">TBD</span></li>
  <li>Related Work Items: <span class="tbd">TBD</span></li>
</ul>

</body>
</html>
"@

# -- Write output ------------------------------------------------------------
$null    = New-Item -ItemType Directory -Path "qa-handoff-report" -Force
$outFile = "qa-handoff-report\SDS2-$Version-RC$RcNumber-QA-Handoff.html"
$html | Out-File -FilePath $outFile -Encoding UTF8
Write-Host ">>> Mock Confluence checklist written to: $outFile"
